# Init the prompt
autoload -Uz promptinit && promptinit
# Enable colors
autoload -U colors && colors
# Use modern completion system
autoload -Uz compinit && compinit
# zsh programmable renamer
autoload -U zmv

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# History settings
setopt histignorealldups sharehistory

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
#eval "$(gdircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Autocomplete with menu interface
setopt menucomplete
zstyle ':completion:*' menu select=1 _complete _ignored _approximate
#PS1='     $?\[\e[0;33m\][\!]\[\e[0m\] \W\[\e[0;35m\]\$\[\e[0m\] '
#PS1='     $?\[\e[0;33m\][\!]\[\e[0m\] \W\[\e[0;35m\]λ\[\e[0m\] '

# source /etc/zsh_command_not_found

WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Set up the prompt
#PROMPT="     %?%{$fg[yellow]%}[%h]%{$reset_color%} %c%{$fg[magenta]%}λ%{$reset_color%} "
#PROMPT="%?	%c%{$fg[magenta]%}λ%{$reset_color%} "
#PROMPT="%?	%c%{$fg[magenta]%}🦎%{$reset_color%} "
#PROMPT="%?	%c%{$fg[magenta]%}🐾%{$reset_color%} "
PROMPT="%?	%c%{$fg[magenta]%}λ%{$reset_color%} "
#RPROMPT="<"

## ALIASES

alias quit=exit
alias gc='git commit -m'
alias ga='git add'
alias gs='git status'
alias prune='git remote update origin --prune'
alias vs="open -a 'Visual Studio Code'"
alias l="ls -GF"
alias R="source ~/.zshrc"

## FUNCTIONS

function g() {
  case "$1" in
    1) cd ~/Developer/code.novotelecom/personal-account-ios ;;
    2) cd ~/Developer/code.mine ;;
    3) cd ~/Study/leetcode.com/problems/minimum-size-subarray-sum/ ;;
    *) declare -f g ;;
  esac
}

function cd! () {
    if [[ ! -e "$1" ]]; then
        mkdir -p "$1" && cd "$1"
    else
        cd "$1"
    fi
}

unalias run-help 2> /dev/null
run-help() {
    man $1 > /dev/null 2>&1
    if [[ $? == 0 ]]; then
        man $1 | awk '/^SYNOPSIS$/,0'
    else
        echo "🦄💀"
    fi
}

# To do C-T in `termite'
# source /etc/profile.d/vte.sh
# export TERMINAL=termite

PATH="/home/razarusu/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/razarusu/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/razarusu/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/razarusu/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/razarusu/perl5"; export PERL_MM_OPT;

#export PATH="/usr/local/opt/node@10/bin:$PATH"
export PATH="/usr/local/Cellar/node@10/10.21.0/bin:$PATH"
export PATH="$HOME/.npm-packages/bin:$PATH"
export PATH="$HOME/Library/Python/3.11/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"

export EDITOR=nvim
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"

## GREETING

echo # newline
echo "Type alias -L to review your aliases."
echo "Type g to list locations."

# Print cool motd
miniman.sh --motd

